DROP TABLE IF EXISTS CORE.CORE_JOBS;

CREATE
    TYPE CORE_JOB_STATUS AS ENUM (
    'IN_SEARCH',
    'DISCARD',
    'SAVED',
    'IN_PROGRESS',
    'APPLIED',
    'INTERVIEWING',
    'NEGOTIATION'
    );

CREATE TABLE CORE.CORE_JOBS
(
    ID              BIGINT       NOT NULL DEFAULT CORE.CORE_NEXT_ID(),
    TITLE           VARCHAR(512) NOT NULL,
    COMPANY         VARCHAR(256) NOT NULL DEFAULT 'UNKNOWN',
    LOCATION        VARCHAR(256),
    DESCRIPTION     TEXT,
    APPLICATION_URL VARCHAR(2048),
    SOURCE          VARCHAR(128) NOT NULL DEFAULT 'UNKNOWN',
    POSTED_DATE     TIMESTAMP,
    IS_REMOTE       BOOLEAN      NOT NULL DEFAULT FALSE,
    IS_EXPIRED      BOOLEAN      NOT NULL DEFAULT FALSE,
    CREATED_BY      BIGINT,
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY      BIGINT,
    UPDATED_AT      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_JOBS_COMPANY ON CORE.CORE_JOBS (COMPANY);
CREATE INDEX IDX_JOBS_SOURCE ON CORE.CORE_JOBS (SOURCE);
CREATE INDEX IDX_JOBS_DATE ON CORE.CORE_JOBS (POSTED_DATE);

DROP TRIGGER IF EXISTS UPDATE_CORE_JOBS_TIMESTAMP ON CORE.CORE_JOBS;

CREATE TRIGGER UPDATE_CORE_JOBS_TIMESTAMP
    BEFORE UPDATE
    ON CORE.CORE_JOBS
    FOR EACH ROW
EXECUTE FUNCTION CORE.CORE_UPDATE_TIMESTAMP();

CREATE TABLE CORE.CORE_USER_JOBS
(
    ID                     BIGINT          NOT NULL DEFAULT CORE.CORE_NEXT_ID(),
    USER_ID                BIGINT          NOT NULL,
    JOB_ID                 BIGINT          NOT NULL,
    JOB_STATUS             CORE_JOB_STATUS NOT NULL DEFAULT 'IN_PROGRESS',
    APPLIED_DATE           TIMESTAMP,
    APPLICATION_NOTES      TEXT,
    RECRUITER_NAME         VARCHAR(256),
    RECRUITER_EMAIL        VARCHAR(256),
    RECRUITER_DIAL_CODE    SMALLINT        NOT NULL DEFAULT 91,
    RECRUITER_PHONE_NUMBER CHAR(15),
    INTERVIEW_NOTES        TEXT,
    NEXT_INTERVIEW_DATE    TIMESTAMP,
    SALARY_RANGE           VARCHAR(128),
    BENEFITS               TEXT,
    REJECTION_REASON       TEXT,
    REJECTION_DATE         TIMESTAMP,
    OFFER_DETAILS          TEXT,
    OFFER_DATE             TIMESTAMP,
    NEGOTIATION_NOTES      TEXT,
    CREATED_BY             BIGINT,
    CREATED_AT             TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY             BIGINT,
    UPDATED_AT             TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT FK1_USER_JOBS_JOB_ID_JOBS_ID FOREIGN KEY (JOB_ID) REFERENCES CORE.CORE_JOBS (ID),
    CONSTRAINT FK2_USER_JOBS_USER_ID_USERS_ID FOREIGN KEY (USER_ID) REFERENCES CORE.CORE_USERS (ID)
);

CREATE INDEX IDX1_USER_JOBS_USER_ID ON CORE.CORE_USER_JOBS (USER_ID);
CREATE INDEX IDX2_USER_JOBS_JOB_ID ON CORE.CORE_USER_JOBS (JOB_ID);
CREATE INDEX IDX3_USER_JOBS_JOB_STATUS ON CORE.CORE_USER_JOBS (JOB_STATUS);

DROP TRIGGER IF EXISTS UPDATE_CORE_USER_JOBS_TIMESTAMP ON CORE.CORE_USER_JOBS;

CREATE TRIGGER UPDATE_CORE_USER_JOBS_TIMESTAMP
    BEFORE UPDATE
    ON CORE.CORE_USER_JOBS
    FOR EACH ROW
EXECUTE FUNCTION CORE.CORE_UPDATE_TIMESTAMP();
