spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/cepl/IdeaProjects/j13n-saas/configfiles
server:
  port: 9991

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
