spring:
  application:
    name: config
  cloud:
    config:
      server:
        bootstrap: true
  profiles:
    active: ${SPRING_PROFILE:default}

endpoints:
  enabled: true

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:9999}/eureka/
  instance:
    prefer-ip-address: true

logging:
  structured:
    format:
      console: gelf
      file: gelf
    json:
      add:
        instanceId: ${INSTANCE_ID:default}
