/*
 * This file is generated by jOOQ.
 */
package io.j13n.core.jooq.public_.enums;


import io.j13n.core.jooq.public_.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum CoreFileSystemType implements EnumType {

    FILE("FILE"),

    DIRECTORY("DIRECTORY");

    private final String literal;

    private CoreFileSystemType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "core_file_system_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static CoreFileSystemType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(CoreFileSystemType.class, literal);
    }
}
