/*
 * This file is generated by jOOQ.
 */
package io.j13n.core.jooq.public_.enums;


import io.j13n.core.jooq.public_.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum CoreFileResourceType implements EnumType {

    STATIC("STATIC"),

    SECURED("SECURED");

    private final String literal;

    private CoreFileResourceType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "core_file_resource_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static CoreFileResourceType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(CoreFileResourceType.class, literal);
    }
}
