/*
 * This file is generated by jOOQ.
 */
package io.j13n.core.jooq.public_.enums;


import io.j13n.core.jooq.public_.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum CoreJobStatus implements EnumType {

    IN_SEARCH("IN_SEARCH"),

    DISCARD("DISCARD"),

    SAVED("SAVED"),

    IN_PROGRESS("IN_PROGRESS"),

    APPLIED("APPLIED"),

    INTERVIEWING("INTERVIEWING"),

    NEGOTIATION("NEGOTIATION");

    private final String literal;

    private CoreJobStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "core_job_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static CoreJobStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(CoreJobStatus.class, literal);
    }
}
