/*
 * This file is generated by jOOQ.
 */
package io.j13n.core.jooq.tables;


import io.j13n.core.jooq.Core;
import io.j13n.core.jooq.Keys;
import io.j13n.core.jooq.tables.CoreUserAuthorities.CoreUserAuthoritiesPath;
import io.j13n.core.jooq.tables.CoreUsers.CoreUsersPath;
import io.j13n.core.jooq.tables.records.CoreAuthoritiesRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CoreAuthorities extends TableImpl<CoreAuthoritiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>core.core_authorities</code>
     */
    public static final CoreAuthorities CORE_AUTHORITIES = new CoreAuthorities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CoreAuthoritiesRecord> getRecordType() {
        return CoreAuthoritiesRecord.class;
    }

    /**
     * The column <code>core.core_authorities.id</code>.
     */
    public final TableField<CoreAuthoritiesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("core.next_id()"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>core.core_authorities.name</code>.
     */
    public final TableField<CoreAuthoritiesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>core.core_authorities.created_at</code>.
     */
    public final TableField<CoreAuthoritiesRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>core.core_authorities.created_by</code>.
     */
    public final TableField<CoreAuthoritiesRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>core.core_authorities.updated_at</code>.
     */
    public final TableField<CoreAuthoritiesRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>core.core_authorities.updated_by</code>.
     */
    public final TableField<CoreAuthoritiesRecord, Long> UPDATED_BY = createField(DSL.name("updated_by"), SQLDataType.BIGINT, this, "");

    private CoreAuthorities(Name alias, Table<CoreAuthoritiesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CoreAuthorities(Name alias, Table<CoreAuthoritiesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>core.core_authorities</code> table reference
     */
    public CoreAuthorities(String alias) {
        this(DSL.name(alias), CORE_AUTHORITIES);
    }

    /**
     * Create an aliased <code>core.core_authorities</code> table reference
     */
    public CoreAuthorities(Name alias) {
        this(alias, CORE_AUTHORITIES);
    }

    /**
     * Create a <code>core.core_authorities</code> table reference
     */
    public CoreAuthorities() {
        this(DSL.name("core_authorities"), null);
    }

    public <O extends Record> CoreAuthorities(Table<O> path, ForeignKey<O, CoreAuthoritiesRecord> childPath, InverseForeignKey<O, CoreAuthoritiesRecord> parentPath) {
        super(path, childPath, parentPath, CORE_AUTHORITIES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CoreAuthoritiesPath extends CoreAuthorities implements Path<CoreAuthoritiesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CoreAuthoritiesPath(Table<O> path, ForeignKey<O, CoreAuthoritiesRecord> childPath, InverseForeignKey<O, CoreAuthoritiesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CoreAuthoritiesPath(Name alias, Table<CoreAuthoritiesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CoreAuthoritiesPath as(String alias) {
            return new CoreAuthoritiesPath(DSL.name(alias), this);
        }

        @Override
        public CoreAuthoritiesPath as(Name alias) {
            return new CoreAuthoritiesPath(alias, this);
        }

        @Override
        public CoreAuthoritiesPath as(Table<?> alias) {
            return new CoreAuthoritiesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Core.CORE;
    }

    @Override
    public UniqueKey<CoreAuthoritiesRecord> getPrimaryKey() {
        return Keys.CORE_AUTHORITIES_PKEY;
    }

    @Override
    public List<UniqueKey<CoreAuthoritiesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.CORE_AUTHORITIES_NAME_KEY);
    }

    private transient CoreUserAuthoritiesPath _coreUserAuthorities;

    /**
     * Get the implicit to-many join path to the
     * <code>core.core_user_authorities</code> table
     */
    public CoreUserAuthoritiesPath coreUserAuthorities() {
        if (_coreUserAuthorities == null)
            _coreUserAuthorities = new CoreUserAuthoritiesPath(this, null, Keys.CORE_USER_AUTHORITIES__CORE_USER_AUTHORITIES_AUTHORITY_ID_FKEY.getInverseKey());

        return _coreUserAuthorities;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>core.core_users</code> table
     */
    public CoreUsersPath coreUsers() {
        return coreUserAuthorities().coreUsers();
    }

    @Override
    public CoreAuthorities as(String alias) {
        return new CoreAuthorities(DSL.name(alias), this);
    }

    @Override
    public CoreAuthorities as(Name alias) {
        return new CoreAuthorities(alias, this);
    }

    @Override
    public CoreAuthorities as(Table<?> alias) {
        return new CoreAuthorities(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CoreAuthorities rename(String name) {
        return new CoreAuthorities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CoreAuthorities rename(Name name) {
        return new CoreAuthorities(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CoreAuthorities rename(Table<?> name) {
        return new CoreAuthorities(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CoreAuthorities where(Condition condition) {
        return new CoreAuthorities(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CoreAuthorities where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CoreAuthorities where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CoreAuthorities where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CoreAuthorities where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CoreAuthorities where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CoreAuthorities where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CoreAuthorities where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CoreAuthorities whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CoreAuthorities whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
