version: "3.9"

services:

  config:
    build:
      context: ./config
    container_name: config
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILE: default
      INSTANCE_ID: config-instance
      GIT_URL: https://github.com/aplygen/j13n-saas
      GIT_USERNAME: lawbringr1
      GIT_PASSWORD: Hobbs1For2President3\
    volumes:
      - ./logs/config:/logs

  eureka:
    build:
      context: ./eureka
    container_name: eureka
    ports:
      - "9999:9999"
    environment:
      INSTANCE_ID: eureka-instance
    volumes:
      - ./logs/eureka:/logs
    depends_on:
      - config

  core:
    build:
      context: ./core
    container_name: core
    ports:
      - "8005:8005"
    environment:
      INSTANCE_ID: core-instance
    volumes:
      - ./logs/core:/logs
    depends_on:
      - eureka
