/*
 * This file is generated by jOOQ.
 */
package io.j13n.core.jooq.core.routines;


import io.j13n.core.jooq.core.Core;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CoreGetCustomEpoch extends AbstractRoutine<Long> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>core.core_get_custom_epoch.RETURN_VALUE</code>.
     */
    public static final Parameter<Long> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public CoreGetCustomEpoch() {
        super("core_get_custom_epoch", Core.CORE, DSL.comment(""), SQLDataType.BIGINT);

        setReturnParameter(RETURN_VALUE);
    }
}
