/*
 * This file is generated by jOOQ.
 */
package io.j13n.core.jooq.core.routines;


import io.j13n.core.jooq.core.Core;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CoreNextId extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>core.core_next_id.result</code>.
     */
    public static final Parameter<Long> RESULT = Internal.createParameter("result", SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public CoreNextId() {
        super("core_next_id", Core.CORE, DSL.comment(""));

        addOutParameter(RESULT);
    }

    /**
     * Get the <code>result</code> parameter OUT value from the routine
     */
    public Long getResult() {
        return get(RESULT);
    }
}
