steps:
  # Build the application
  - name: 'maven:3.8.4-openjdk-21'
    entrypoint: mvn
    args: ['package', '-DskipTests']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/core:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/core:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'core'
      - '--image'
      - 'gcr.io/$PROJECT_ID/core:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'SPRING_PROFILES_ACTIVE=gcp'

images:
  - 'gcr.io/$PROJECT_ID/core:$COMMIT_SHA'