/*
 * This file is generated by jOOQ.
 */
package io.j13n.core.jooq.core.tables.records;


import io.j13n.core.enums.JobStatus;
import io.j13n.core.jooq.core.tables.CoreUserJobs;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CoreUserJobsRecord extends UpdatableRecordImpl<CoreUserJobsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>core.core_user_jobs.id</code>.
     */
    public CoreUserJobsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>core.core_user_jobs.user_id</code>.
     */
    public CoreUserJobsRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>core.core_user_jobs.job_id</code>.
     */
    public CoreUserJobsRecord setJobId(Long value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.job_id</code>.
     */
    public Long getJobId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>core.core_user_jobs.job_status</code>.
     */
    public CoreUserJobsRecord setJobStatus(JobStatus value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.job_status</code>.
     */
    public JobStatus getJobStatus() {
        return (JobStatus) get(3);
    }

    /**
     * Setter for <code>core.core_user_jobs.applied_date</code>.
     */
    public CoreUserJobsRecord setAppliedDate(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.applied_date</code>.
     */
    public LocalDateTime getAppliedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>core.core_user_jobs.application_notes</code>.
     */
    public CoreUserJobsRecord setApplicationNotes(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.application_notes</code>.
     */
    public String getApplicationNotes() {
        return (String) get(5);
    }

    /**
     * Setter for <code>core.core_user_jobs.recruiter_name</code>.
     */
    public CoreUserJobsRecord setRecruiterName(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.recruiter_name</code>.
     */
    public String getRecruiterName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>core.core_user_jobs.recruiter_email</code>.
     */
    public CoreUserJobsRecord setRecruiterEmail(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.recruiter_email</code>.
     */
    public String getRecruiterEmail() {
        return (String) get(7);
    }

    /**
     * Setter for <code>core.core_user_jobs.recruiter_dial_code</code>.
     */
    public CoreUserJobsRecord setRecruiterDialCode(Short value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.recruiter_dial_code</code>.
     */
    public Short getRecruiterDialCode() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>core.core_user_jobs.recruiter_phone_number</code>.
     */
    public CoreUserJobsRecord setRecruiterPhoneNumber(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.recruiter_phone_number</code>.
     */
    public String getRecruiterPhoneNumber() {
        return (String) get(9);
    }

    /**
     * Setter for <code>core.core_user_jobs.interview_notes</code>.
     */
    public CoreUserJobsRecord setInterviewNotes(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.interview_notes</code>.
     */
    public String getInterviewNotes() {
        return (String) get(10);
    }

    /**
     * Setter for <code>core.core_user_jobs.next_interview_date</code>.
     */
    public CoreUserJobsRecord setNextInterviewDate(LocalDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.next_interview_date</code>.
     */
    public LocalDateTime getNextInterviewDate() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>core.core_user_jobs.salary_range</code>.
     */
    public CoreUserJobsRecord setSalaryRange(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.salary_range</code>.
     */
    public String getSalaryRange() {
        return (String) get(12);
    }

    /**
     * Setter for <code>core.core_user_jobs.benefits</code>.
     */
    public CoreUserJobsRecord setBenefits(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.benefits</code>.
     */
    public String getBenefits() {
        return (String) get(13);
    }

    /**
     * Setter for <code>core.core_user_jobs.rejection_reason</code>.
     */
    public CoreUserJobsRecord setRejectionReason(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.rejection_reason</code>.
     */
    public String getRejectionReason() {
        return (String) get(14);
    }

    /**
     * Setter for <code>core.core_user_jobs.rejection_date</code>.
     */
    public CoreUserJobsRecord setRejectionDate(LocalDateTime value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.rejection_date</code>.
     */
    public LocalDateTime getRejectionDate() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>core.core_user_jobs.offer_details</code>.
     */
    public CoreUserJobsRecord setOfferDetails(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.offer_details</code>.
     */
    public String getOfferDetails() {
        return (String) get(16);
    }

    /**
     * Setter for <code>core.core_user_jobs.offer_date</code>.
     */
    public CoreUserJobsRecord setOfferDate(LocalDateTime value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.offer_date</code>.
     */
    public LocalDateTime getOfferDate() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>core.core_user_jobs.negotiation_notes</code>.
     */
    public CoreUserJobsRecord setNegotiationNotes(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.negotiation_notes</code>.
     */
    public String getNegotiationNotes() {
        return (String) get(18);
    }

    /**
     * Setter for <code>core.core_user_jobs.created_by</code>.
     */
    public CoreUserJobsRecord setCreatedBy(Long value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>core.core_user_jobs.created_at</code>.
     */
    public CoreUserJobsRecord setCreatedAt(LocalDateTime value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(20);
    }

    /**
     * Setter for <code>core.core_user_jobs.updated_by</code>.
     */
    public CoreUserJobsRecord setUpdatedBy(Long value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>core.core_user_jobs.updated_at</code>.
     */
    public CoreUserJobsRecord setUpdatedAt(LocalDateTime value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>core.core_user_jobs.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoreUserJobsRecord
     */
    public CoreUserJobsRecord() {
        super(CoreUserJobs.CORE_USER_JOBS);
    }

    /**
     * Create a detached, initialised CoreUserJobsRecord
     */
    public CoreUserJobsRecord(Long id, Long userId, Long jobId, JobStatus jobStatus, LocalDateTime appliedDate, String applicationNotes, String recruiterName, String recruiterEmail, Short recruiterDialCode, String recruiterPhoneNumber, String interviewNotes, LocalDateTime nextInterviewDate, String salaryRange, String benefits, String rejectionReason, LocalDateTime rejectionDate, String offerDetails, LocalDateTime offerDate, String negotiationNotes, Long createdBy, LocalDateTime createdAt, Long updatedBy, LocalDateTime updatedAt) {
        super(CoreUserJobs.CORE_USER_JOBS);

        setId(id);
        setUserId(userId);
        setJobId(jobId);
        setJobStatus(jobStatus);
        setAppliedDate(appliedDate);
        setApplicationNotes(applicationNotes);
        setRecruiterName(recruiterName);
        setRecruiterEmail(recruiterEmail);
        setRecruiterDialCode(recruiterDialCode);
        setRecruiterPhoneNumber(recruiterPhoneNumber);
        setInterviewNotes(interviewNotes);
        setNextInterviewDate(nextInterviewDate);
        setSalaryRange(salaryRange);
        setBenefits(benefits);
        setRejectionReason(rejectionReason);
        setRejectionDate(rejectionDate);
        setOfferDetails(offerDetails);
        setOfferDate(offerDate);
        setNegotiationNotes(negotiationNotes);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
