/*
 * This file is generated by jOOQ.
 */
package io.j13n.core.jooq.core.tables.records;


import io.j13n.core.jooq.core.tables.CoreJobs;
import io.j13n.core.jooq.public_.enums.CoreJobStatus;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CoreJobsRecord extends UpdatableRecordImpl<CoreJobsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>core.core_jobs.id</code>.
     */
    public CoreJobsRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>core.core_jobs.user_id</code>.
     */
    public CoreJobsRecord setUserId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>core.core_jobs.title</code>.
     */
    public CoreJobsRecord setTitle(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>core.core_jobs.company</code>.
     */
    public CoreJobsRecord setCompany(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.company</code>.
     */
    public String getCompany() {
        return (String) get(3);
    }

    /**
     * Setter for <code>core.core_jobs.location</code>.
     */
    public CoreJobsRecord setLocation(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.location</code>.
     */
    public String getLocation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>core.core_jobs.description</code>.
     */
    public CoreJobsRecord setDescription(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>core.core_jobs.application_url</code>.
     */
    public CoreJobsRecord setApplicationUrl(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.application_url</code>.
     */
    public String getApplicationUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>core.core_jobs.source</code>.
     */
    public CoreJobsRecord setSource(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.source</code>.
     */
    public String getSource() {
        return (String) get(7);
    }

    /**
     * Setter for <code>core.core_jobs.posted_date</code>.
     */
    public CoreJobsRecord setPostedDate(LocalDateTime value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.posted_date</code>.
     */
    public LocalDateTime getPostedDate() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>core.core_jobs.is_remote</code>.
     */
    public CoreJobsRecord setIsRemote(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.is_remote</code>.
     */
    public Boolean getIsRemote() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>core.core_jobs.status</code>.
     */
    public CoreJobsRecord setStatus(CoreJobStatus value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.status</code>.
     */
    public CoreJobStatus getStatus() {
        return (CoreJobStatus) get(10);
    }

    /**
     * Setter for <code>core.core_jobs.created_by</code>.
     */
    public CoreJobsRecord setCreatedBy(Long value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>core.core_jobs.created_at</code>.
     */
    public CoreJobsRecord setCreatedAt(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>core.core_jobs.updated_by</code>.
     */
    public CoreJobsRecord setUpdatedBy(Long value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>core.core_jobs.updated_at</code>.
     */
    public CoreJobsRecord setUpdatedAt(LocalDateTime value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>core.core_jobs.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoreJobsRecord
     */
    public CoreJobsRecord() {
        super(CoreJobs.CORE_JOBS);
    }

    /**
     * Create a detached, initialised CoreJobsRecord
     */
    public CoreJobsRecord(Long id, Long userId, String title, String company, String location, String description, String applicationUrl, String source, LocalDateTime postedDate, Boolean isRemote, CoreJobStatus status, Long createdBy, LocalDateTime createdAt, Long updatedBy, LocalDateTime updatedAt) {
        super(CoreJobs.CORE_JOBS);

        setId(id);
        setUserId(userId);
        setTitle(title);
        setCompany(company);
        setLocation(location);
        setDescription(description);
        setApplicationUrl(applicationUrl);
        setSource(source);
        setPostedDate(postedDate);
        setIsRemote(isRemote);
        setStatus(status);
        setCreatedBy(createdBy);
        setCreatedAt(createdAt);
        setUpdatedBy(updatedBy);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
