/*
 * This file is generated by jOOQ.
 */
package io.j13n.core.jooq.core.tables.records;


import io.j13n.core.jooq.core.tables.CoreAuthorities;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CoreAuthoritiesRecord extends UpdatableRecordImpl<CoreAuthoritiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>core.core_authorities.id</code>.
     */
    public CoreAuthoritiesRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>core.core_authorities.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>core.core_authorities.name</code>.
     */
    public CoreAuthoritiesRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>core.core_authorities.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>core.core_authorities.created_at</code>.
     */
    public CoreAuthoritiesRecord setCreatedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>core.core_authorities.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>core.core_authorities.created_by</code>.
     */
    public CoreAuthoritiesRecord setCreatedBy(Long value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>core.core_authorities.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>core.core_authorities.updated_at</code>.
     */
    public CoreAuthoritiesRecord setUpdatedAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>core.core_authorities.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>core.core_authorities.updated_by</code>.
     */
    public CoreAuthoritiesRecord setUpdatedBy(Long value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>core.core_authorities.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoreAuthoritiesRecord
     */
    public CoreAuthoritiesRecord() {
        super(CoreAuthorities.CORE_AUTHORITIES);
    }

    /**
     * Create a detached, initialised CoreAuthoritiesRecord
     */
    public CoreAuthoritiesRecord(Long id, String name, LocalDateTime createdAt, Long createdBy, LocalDateTime updatedAt, Long updatedBy) {
        super(CoreAuthorities.CORE_AUTHORITIES);

        setId(id);
        setName(name);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        resetTouchedOnNotNull();
    }
}
