spring:
  application:
    name: eureka
  config:
    import: configserver:http://${CLOUD_CONFIG_SERVER:localhost}:${CLOUD_CONFIG_SERVER_PORT:9991}/
  profiles:
    active: ${SPRING_PROFILE:default}

server:
  port: 9999
