/*
 * This file is generated by jOOQ.
 */
package io.j13n.core.jooq;


import io.j13n.core.jooq.tables.CoreAuthorities;
import io.j13n.core.jooq.tables.CoreFileSystem;
import io.j13n.core.jooq.tables.CoreUserAuthorities;
import io.j13n.core.jooq.tables.CoreUsers;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Core extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>core</code>
     */
    public static final Core CORE = new Core();

    /**
     * The table <code>core.core_authorities</code>.
     */
    public final CoreAuthorities CORE_AUTHORITIES = CoreAuthorities.CORE_AUTHORITIES;

    /**
     * The table <code>core.core_file_system</code>.
     */
    public final CoreFileSystem CORE_FILE_SYSTEM = CoreFileSystem.CORE_FILE_SYSTEM;

    /**
     * The table <code>core.core_user_authorities</code>.
     */
    public final CoreUserAuthorities CORE_USER_AUTHORITIES = CoreUserAuthorities.CORE_USER_AUTHORITIES;

    /**
     * The table <code>core.core_users</code>.
     */
    public final CoreUsers CORE_USERS = CoreUsers.CORE_USERS;

    /**
     * No further instances allowed
     */
    private Core() {
        super(DSL.name("core"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CoreAuthorities.CORE_AUTHORITIES,
            CoreFileSystem.CORE_FILE_SYSTEM,
            CoreUserAuthorities.CORE_USER_AUTHORITIES,
            CoreUsers.CORE_USERS
        );
    }
}
