/*
 * This file is generated by jOOQ.
 */
package io.j13n.core.jooq;


import io.j13n.core.jooq.tables.CoreFileSystem;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in core.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_FILE_SYSTEM_CODE_NAME = Internal.createIndex(DSL.name("idx_file_system_code_name"), CoreFileSystem.CORE_FILE_SYSTEM, new OrderField[] { CoreFileSystem.CORE_FILE_SYSTEM.USER_ID, CoreFileSystem.CORE_FILE_SYSTEM.NAME }, false);
    public static final Index IDX_FILE_SYSTEM_FILE_RESOURCE_TYPE_FILE_SYSTEM_TYPE_PARENT_ID = Internal.createIndex(DSL.name("idx_file_system_file_resource_type_file_system_type_parent_id"), CoreFileSystem.CORE_FILE_SYSTEM, new OrderField[] { CoreFileSystem.CORE_FILE_SYSTEM.FILE_RESOURCE_TYPE, CoreFileSystem.CORE_FILE_SYSTEM.FILE_SYSTEM_TYPE, CoreFileSystem.CORE_FILE_SYSTEM.PARENT_ID }, false);
    public static final Index IDX_FILE_SYSTEM_USER_ID = Internal.createIndex(DSL.name("idx_file_system_user_id"), CoreFileSystem.CORE_FILE_SYSTEM, new OrderField[] { CoreFileSystem.CORE_FILE_SYSTEM.USER_ID }, false);
    public static final Index IDX_FILE_SYSTEM_USER_ID_FILE_RESOURCE_TYPE_FILE_SYSTEM_TYPE = Internal.createIndex(DSL.name("idx_file_system_user_id_file_resource_type_file_system_type"), CoreFileSystem.CORE_FILE_SYSTEM, new OrderField[] { CoreFileSystem.CORE_FILE_SYSTEM.USER_ID, CoreFileSystem.CORE_FILE_SYSTEM.FILE_RESOURCE_TYPE, CoreFileSystem.CORE_FILE_SYSTEM.FILE_SYSTEM_TYPE }, false);
}
