spring:
  datasource:
    url: jdbc:postgresql:///${CLOUD_SQL_CONNECTION_NAME}/${DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    gcp:
      storage:
        bucket-name: ${GCP_STORAGE_BUCKET}
        project-id: ${GCP_PROJECT_ID}

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    io.j13n: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Security configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours

# Service configuration
service:
  instance:
    id: ${INSTANCE_ID:default}