---
spring:
  application:
    name: core
  datasource:
    url: jdbc:postgresql://localhost:5432/core
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: core
server:
  port: 8080
google:
  api:
    key: "${GOOGLE_API_KEY}"
  cse:
    id: "${GOOGLE_CSE_ID}"
tavily:
  api:
    key: "${TAVILY_API_KEY}"
openai:
  api:
    key: "${OPENAI_API_KEY}"
    model: gpt-4-turbo-preview
    temperature: 0.3
    max-tokens: 1000
jwt:
  secret: "${JWT_SECRET:j13nSecretKeyForJWTTokenGenerationAndVerificationPurposes}"
  expiration: 86400000
