---
spring:
  application:
    name: core
  datasource:
    url: jdbc:postgresql://localhost:5432/core
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: core
  threads:
    virtual:
      enabled: true

aws:
  accessKeyId: aosdhj0813ued0813
  secretKey: oqwijd0813ue8091
  region: ap-south-2
  bucket:
    name: j13n

server:
  port: 8080
google:
  api:
    key: "${GOOGLE_API_KEY:123124214}"
  cse:
    id: "${GOOGLE_CSE_ID:12341242143}"
tavily:
  api:
    key: "${TAVILY_API_KEY:2132141251234}"
openai:
  api:
    key: "${OPENAI_API_KEY:1203i12094129034}"
    model: gpt-4-turbo-preview
    temperature: 0.3
    max-tokens: 1000
jwt:
  secret: "${JWT_SECRET:j13nSecretKeyForJWTTokenGenerationAndVerificationPurposes}"
  expiration: 86400000
