---
spring:
  application:
    name: core
  config:
    import: "configserver:http://${CLOUD_CONFIG_SERVER:localhost}:${CLOUD_CONFIG_SERVER_PORT:8888}/"
  profiles:
    active: "${SPRING_PROFILE:default}"
  http:
    codecs:
      max-in-memory-size: 10MB
server:
  port: 8080
