---
spring:
  application:
    name: core
  config:
    import: "configserver:http://${CLOUD_CONFIG_SERVER:localhost}:${CLOUD_CONFIG_SERVER_PORT:8888}/"
  profiles:
    active: "${SPRING_PROFILE:default}"
  http:
    codecs:
      max-in-memory-size: 10MB
  threads:
    virtual:
      enabled: true

management:
  metrics:
    tags:
      application: "${INSTANCE_ENVIRONMENT:LOCAL}-${spring.application.name}-${INSTANCE_ID:default}"

server:
  port: 8005
