---
spring:
  application:
    name: core
  config:
    import: "configserver:http://${CLOUD_CONFIG_SERVER:localhost}:${CLOUD_CONFIG_SERVER_PORT:9991}/"
  profiles:
    active: "${SPRING_PROFILE:default}"
  http:
    codecs:
      max-in-memory-size: 10MB
  threads:
    virtual:
      enabled: true
server:
  port: 9992
