/*
 * This file is generated by jOOQ.
 */
package io.j13n.core.jooq.core;


import io.j13n.core.jooq.core.routines.CoreGetCustomEpoch;
import io.j13n.core.jooq.core.routines.CoreNextId;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in core.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>core.core_get_custom_epoch</code>
     */
    public static Long coreGetCustomEpoch(
          Configuration configuration
    ) {
        CoreGetCustomEpoch f = new CoreGetCustomEpoch();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>core.core_get_custom_epoch</code> as a field.
     */
    public static Field<Long> coreGetCustomEpoch() {
        CoreGetCustomEpoch f = new CoreGetCustomEpoch();

        return f.asField();
    }

    /**
     * Call <code>core.core_next_id</code>
     */
    public static Long coreNextId(
          Configuration configuration
    ) {
        CoreNextId p = new CoreNextId();

        p.execute(configuration);
        return p.getResult();
    }
}
