/*
 * This file is generated by jOOQ.
 */
package io.j13n.core.jooq.core;


import io.j13n.core.jooq.core.tables.CoreAuthorities;
import io.j13n.core.jooq.core.tables.CoreFileSystem;
import io.j13n.core.jooq.core.tables.CoreUserAuthorities;
import io.j13n.core.jooq.core.tables.CoreUsers;


/**
 * Convenience access to all tables in core.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>core.core_authorities</code>.
     */
    public static final CoreAuthorities CORE_AUTHORITIES = CoreAuthorities.CORE_AUTHORITIES;

    /**
     * The table <code>core.core_file_system</code>.
     */
    public static final CoreFileSystem CORE_FILE_SYSTEM = CoreFileSystem.CORE_FILE_SYSTEM;

    /**
     * The table <code>core.core_user_authorities</code>.
     */
    public static final CoreUserAuthorities CORE_USER_AUTHORITIES = CoreUserAuthorities.CORE_USER_AUTHORITIES;

    /**
     * The table <code>core.core_users</code>.
     */
    public static final CoreUsers CORE_USERS = CoreUsers.CORE_USERS;
}
